"""
data_intelligence.py
====================
Task 1 — Data Intelligence & Profiling

Produces reports/data_intelligence_report.md covering:
  - Per-column distribution summaries
  - Missing-value pattern analysis (MCAR / MNAR detection)
  - Outlier detection (IQR, z-score, implausible dates)
  - Correlation / high-dependency detection
  - Association-rule mining (mlxtend apriori on categorical fields)
  - Validation-rule violations (from load_and_validate)
  - Train vs. test drift (PSI / KS-test per feature)
  - Record-level data-quality score (0–1)
  - Batch-level data-quality score
  - Servicer conflict analysis
"""

import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from scipy import stats
import yaml
import json

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parents[2]


def load_cfg(cfg_path=None):
    p = cfg_path or ROOT / "config.yaml"
    with open(p) as f:
        return yaml.safe_load(f)


# ── PSI helper ──────────────────────────────────────────────────────────────
def psi(expected: np.ndarray, actual: np.ndarray, buckets: int = 10) -> float:
    """Population Stability Index between two numeric arrays."""
    breaks = np.percentile(expected, np.linspace(0, 100, buckets + 1))
    breaks = np.unique(breaks)
    if len(breaks) < 2:
        return 0.0
    e_counts, _ = np.histogram(expected, bins=breaks)
    a_counts, _ = np.histogram(actual,   bins=breaks)
    e_pct = (e_counts + 1e-6) / (len(expected) + 1e-6 * buckets)
    a_pct = (a_counts + 1e-6) / (len(actual)   + 1e-6 * buckets)
    return float(np.sum((a_pct - e_pct) * np.log(a_pct / e_pct + 1e-10)))


def ks_stat(s1: pd.Series, s2: pd.Series) -> float:
    s1 = s1.dropna().astype(float)
    s2 = s2.dropna().astype(float)
    if len(s1) < 5 or len(s2) < 5:
        return 0.0
    return float(stats.ks_2samp(s1, s2).statistic)


# ── DQ score ───────────────────────────────────────────────────────────────
def record_dq_score(df: pd.DataFrame, violations: pd.DataFrame) -> pd.Series:
    """
    Composite record-level DQ score ∈ [0,1] (higher = better quality).
    Components:
      - completeness: fraction of non-null fields
      - validity: 0 if the record has any ERROR-severity violation
      - outlier penalty: applied if current_balance >> original_balance
    """
    total_cols = len(df.columns)
    completeness = df.notna().sum(axis=1) / total_cols

    error_loans = set()
    if len(violations):
        error_viol = violations[violations["severity"] == "error"]
        error_loans = set(error_viol["loan_id"].unique())

    validity = pd.Series(1.0, index=df.index)
    validity[df["loan_id"].isin(error_loans)] = 0.5

    # Outlier penalty
    bal_ratio = df["current_balance"] / df["original_balance"].replace(0, np.nan)
    outlier_pen = (bal_ratio > 2.0).astype(float) * 0.3

    score = (completeness * 0.5 + validity * 0.4 - outlier_pen * 0.1).clip(0, 1)
    return score


def run_profiling(cfg: dict, dfs: dict, violations: pd.DataFrame) -> str:
    """Main profiling function. Returns the markdown report as a string."""
    plots_dir = ROOT / cfg["PATHS"].get("plots", "reports/plots")
    plots_dir.mkdir(parents=True, exist_ok=True)

    train = dfs.get("train", pd.DataFrame())
    test  = dfs.get("test",  pd.DataFrame())
    static = dfs.get("static", pd.DataFrame())
    svc    = dfs.get("servicer", pd.DataFrame())
    panel  = pd.concat([train, test], ignore_index=True)

    lines = []
    def h(text, level=2): lines.append(f"\n{'#'*level} {text}\n")
    def p(text):          lines.append(text + "\n")
    def table(df):        lines.append(df.to_markdown(index=False) + "\n")

    lines.append("# Data Intelligence & Profiling Report\n")
    p(f"Generated by `src/profiling/data_intelligence.py` on {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}.")
    p(f"**Dataset**: {len(panel):,} panel rows × {panel.shape[1]} columns | "
      f"{panel['loan_id'].nunique():,} unique loans | "
      f"months {panel['month_index'].min()}–{panel['month_index'].max()}")

    # ── 1. Distribution summaries ─────────────────────────────────────────
    h("1. Column Distribution Summaries", 2)

    numeric_cols = panel.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols     = panel.select_dtypes(include=["object","category"]).columns.tolist()

    h("1.1 Numeric Columns", 3)
    num_stats = []
    for col in numeric_cols[:20]:  # cap for readability
        s = panel[col].dropna()
        if len(s) == 0: continue
        num_stats.append({
            "Column":  col,
            "Count":   f"{s.count():,}",
            "Mean":    f"{s.mean():.2f}",
            "Median":  f"{s.median():.2f}",
            "Std":     f"{s.std():.2f}",
            "Min":     f"{s.min():.2f}",
            "Max":     f"{s.max():.2f}",
            "Skew":    f"{s.skew():.2f}",
            "p5":      f"{s.quantile(0.05):.2f}",
            "p95":     f"{s.quantile(0.95):.2f}",
        })
    table(pd.DataFrame(num_stats))

    h("1.2 Categorical Columns", 3)
    cat_stats = []
    for col in cat_cols[:20]:
        s = panel[col].dropna()
        vc = s.value_counts()
        cat_stats.append({
            "Column":       col,
            "Cardinality":  s.nunique(),
            "Top1":         vc.index[0] if len(vc) else "",
            "Top1_Pct":     f"{100*vc.iloc[0]/len(s):.1f}%" if len(vc) else "",
            "Rare(<1%)":    int((vc / len(s) < 0.01).sum()),
            "Missing%":     f"{100*panel[col].isna().mean():.1f}%",
        })
    table(pd.DataFrame(cat_stats))

    # ── 2. Missing-value analysis ─────────────────────────────────────────
    h("2. Missing-Value Pattern Analysis", 2)

    miss = (panel.isna().sum() / len(panel) * 100).sort_values(ascending=False)
    miss = miss[miss > 0]
    miss_df = pd.DataFrame({"Column": miss.index, "Missing_%": miss.values.round(2)})
    table(miss_df)

    # MNAR check: is document_status missing correlated with default?
    if "document_status" in panel.columns and "default_flag" in panel.columns:
        doc_missing = panel["document_status"].isna()
        default_rate_missing = panel.loc[doc_missing, "default_flag"].mean()
        default_rate_present = panel.loc[~doc_missing, "default_flag"].mean()
        p(f"\n**MNAR signal**: `document_status` missing → default rate = "
          f"**{default_rate_missing:.3f}** vs present → **{default_rate_present:.3f}** "
          f"({'⚠ MNAR suspected' if default_rate_missing > default_rate_present * 1.5 else 'MCAR plausible'})")

    # Missingness correlation heatmap
    miss_matrix = panel[panel.columns[panel.isna().any()]].isna().astype(int)
    if len(miss_matrix.columns) > 1:
        fig, ax = plt.subplots(figsize=(8, 4))
        corr_m = miss_matrix.corr()
        sns.heatmap(corr_m, ax=ax, cmap="Reds", annot=False)
        ax.set_title("Missingness Correlation Heatmap")
        plt.tight_layout()
        fig.savefig(plots_dir / "missingness_heatmap.png", dpi=100)
        plt.close(fig)
        p(f"![Missingness Heatmap](plots/missingness_heatmap.png)")

    # ── 3. Outlier detection ──────────────────────────────────────────────
    h("3. Outlier Detection", 2)

    outlier_summary = []
    for col in ["current_balance", "interest_rate", "days_past_due", "loan_age_months"]:
        if col not in panel.columns: continue
        s = panel[col].dropna()
        q1, q3 = s.quantile(0.25), s.quantile(0.75)
        iqr = q3 - q1
        lo, hi = q1 - 3*iqr, q3 + 3*iqr
        n_out = int(((s < lo) | (s > hi)).sum())
        z_out = int((np.abs(stats.zscore(s)) > 4).sum())
        outlier_summary.append({"Column": col, "IQR_outliers": n_out,
                                 "ZScore>4_outliers": z_out,
                                 "IQR_lo": round(lo,2), "IQR_hi": round(hi,2)})
    table(pd.DataFrame(outlier_summary))

    # Date violations
    if "origination_month" in panel.columns and "reporting_month" in panel.columns:
        bad_dates = (panel["origination_month"] > panel["reporting_month"]).sum()
        p(f"\n**Date violations**: `origination_month > reporting_month` in **{bad_dates:,}** records")

    # ── 4. Correlation / high-dependency detection ────────────────────────
    h("4. Feature Correlation Analysis", 2)

    numeric_for_corr = panel[numeric_cols].dropna(thresh=len(panel)//2)
    if len(numeric_for_corr.columns) > 2:
        corr = numeric_for_corr.corr().abs()
        upper = corr.where(np.triu(np.ones_like(corr, dtype=bool), k=1))
        high_corr = upper.stack()[upper.stack() > 0.8]
        if len(high_corr):
            hc_df = pd.DataFrame([(i, j, round(v,3)) for (i,j),v in high_corr.items()],
                                  columns=["Feature_A","Feature_B","Correlation"])
            p("**High-correlation pairs (|r| > 0.8):**")
            table(hc_df)
        else:
            p("No highly correlated feature pairs detected (|r| > 0.8 threshold).")

    # ── 5. Validation-rule violations ────────────────────────────────────
    h("5. Validation Rule Violations", 2)

    if len(violations):
        vsum = violations.groupby(["rule_id","rule_name","severity"]).size().reset_index(name="count")
        vsum["pct_of_panel"] = (vsum["count"] / len(panel) * 100).round(3)
        table(vsum)
    else:
        p("No rule violations detected.")

    # ── 6. Train vs. Test Drift ───────────────────────────────────────────
    h("6. Train vs. Test Distribution Drift", 2)

    drift_rows = []
    if len(train) and len(test):
        for col in numeric_cols:
            if col in train.columns and col in test.columns:
                p_val = psi(train[col].dropna().values, test[col].dropna().values)
                ks    = ks_stat(train[col], test[col])
                flag  = "⚠ HIGH DRIFT" if p_val > 0.25 or ks > 0.2 else "OK"
                drift_rows.append({"Column": col, "PSI": round(p_val,4),
                                   "KS_stat": round(ks,4), "Status": flag})
    if drift_rows:
        table(pd.DataFrame(drift_rows))

    # ── 7. Record-level DQ Score ──────────────────────────────────────────
    h("7. Data-Quality Scores", 2)

    panel["dq_score"] = record_dq_score(panel, violations)
    batch_score = panel["dq_score"].mean()

    p(f"**Batch-level DQ score**: **{batch_score:.3f}** / 1.000")
    p(f"Distribution: mean={panel['dq_score'].mean():.3f}, "
      f"p10={panel['dq_score'].quantile(0.10):.3f}, "
      f"p50={panel['dq_score'].quantile(0.50):.3f}, "
      f"p90={panel['dq_score'].quantile(0.90):.3f}")

    # DQ score histogram
    fig, ax = plt.subplots(figsize=(7,3))
    ax.hist(panel["dq_score"], bins=30, color="#2563EB", edgecolor="white", alpha=0.8)
    ax.set_xlabel("DQ Score"); ax.set_ylabel("Count")
    ax.set_title("Record-Level Data Quality Score Distribution")
    plt.tight_layout()
    fig.savefig(plots_dir / "dq_score_hist.png", dpi=100)
    plt.close(fig)
    p(f"![DQ Score Distribution](plots/dq_score_hist.png)")

    # ── 8. Servicer conflict analysis ─────────────────────────────────────
    h("8. Servicer Update Conflict Analysis", 2)

    if len(svc):
        conflict_rate = svc["conflict_flag"].mean() if "conflict_flag" in svc.columns else 0
        p(f"Servicer feed contains **{len(svc):,}** update records.")
        p(f"Conflict rate (status mismatch vs primary): **{conflict_rate:.1%}**")
        # Top conflicting loans
        if "conflict_flag" in svc.columns:
            top_conflict = (svc[svc["conflict_flag"]==1]
                             .groupby("loan_id").size()
                             .sort_values(ascending=False)
                             .head(10)
                             .reset_index(name="n_conflicts"))
            p("Top 10 loans by conflict frequency:")
            table(top_conflict)

    # ── 9. Association rules (categorical) ────────────────────────────────
    h("9. Categorical Association Patterns", 2)

    cat_subset_cols = ["credit_score_band","ltv_band","loan_purpose","current_status"]
    cat_subset_cols = [c for c in cat_subset_cols if c in panel.columns]
    if cat_subset_cols:
        try:
            from mlxtend.preprocessing import TransactionEncoder
            from mlxtend.frequent_patterns import apriori, association_rules as _ars

            cat_df = panel[cat_subset_cols].dropna().astype(str)
            # Create item strings like "credit_score_band=Good"
            transactions = cat_df.apply(
                lambda row: [f"{col}={val}" for col, val in row.items()], axis=1
            ).tolist()
            te = TransactionEncoder()
            te_array = te.fit(transactions).transform(transactions)
            freq_items = apriori(pd.DataFrame(te_array, columns=te.columns_),
                                 min_support=0.05, use_colnames=True)
            if len(freq_items):
                rules = _ars(freq_items, metric="lift", min_threshold=1.5)
                rules = rules.sort_values("lift", ascending=False).head(10)
                rules_out = rules[["antecedents","consequents","support","confidence","lift"]].copy()
                rules_out["antecedents"] = rules_out["antecedents"].apply(lambda x: ", ".join(sorted(x)))
                rules_out["consequents"] = rules_out["consequents"].apply(lambda x: ", ".join(sorted(x)))
                for col in ["support","confidence","lift"]:
                    rules_out[col] = rules_out[col].round(3)
                p("Top 10 association rules (lift > 1.5):")
                table(rules_out)
        except Exception as e:
            p(f"*Association-rule mining skipped: {e}*")

    # ── 10. Top anomaly flags from data profiling ─────────────────────────
    h("10. Top Data Quality Issues Summary", 2)

    issues = []
    if len(violations):
        for _, vrow in violations.head(20).iterrows():
            issues.append({
                "loan_id":     vrow["loan_id"],
                "month_index": vrow["month_index"],
                "issue":       f"[{vrow['rule_id']}] {vrow['rule_name']}",
                "severity":    vrow["severity"],
                "details":     vrow["details"],
            })
    if issues:
        table(pd.DataFrame(issues))
    else:
        p("No critical data quality issues found.")

    return "\n".join(lines)


def run(cfg=None):
    if cfg is None:
        cfg = load_cfg()

    from src.data.load_and_validate import load_all, validate_and_save
    dfs = load_all(cfg)
    violations = validate_and_save(cfg, dfs)

    report_text = run_profiling(cfg, dfs, violations)

    reports_dir = ROOT / cfg["PATHS"]["reports"]
    reports_dir.mkdir(parents=True, exist_ok=True)
    (reports_dir / "data_intelligence_report.md").write_text(report_text, encoding="utf-8")
    print(f"  ✓ data_intelligence_report.md written to {reports_dir}")
    return dfs, violations


if __name__ == "__main__":
    run()
